on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: oss-actions/pr-title-lint@v0
        with:
          title: ${{ github.event.pull_request.title }}
          summary: true
          into: master
